services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_password
      - MYSQL_DATABASE=capstone
      - MYSQL_HOST=mysql
    volumes:
      - mysql_data:/var/lib/mysql
    
volumes:
  mysql_data:
