// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"encoding/json"
)

type User struct {
	ID          int32
	Firstname   string
	Lastname    string
	Preferences json.RawMessage
}
