// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const addUser = `-- name: AddUser :execresult
INSERT INTO ` + "`" + `Users` + "`" + ` (` + "`" + `FirstName` + "`" + ` , ` + "`" + `LastName` + "`" + `, ` + "`" + `Preferences` + "`" + `)
VALUES(?,?,?)
`

type AddUserParams struct {
	Firstname   string
	Lastname    string
	Preferences json.RawMessage
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUser, arg.Firstname, arg.Lastname, arg.Preferences)
}
