// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"encoding/json"
)

type User struct {
	UserID       int32
	FirstName    string
	PasswordHash string
	LastName     string
	Email        string
	Preferences  json.RawMessage
	CreatedAt    sql.NullTime
}
